import type {
  AcquisitionInstrument,
  AuditLog,
  Commitment,
  ConnectorHealth,
  Credit,
  DemoState,
  Divergence,
  DocumentReference,
  EventRelation,
  ItemVariant,
  Location,
  LogisticsEvent,
  LogisticsUnit,
  Lot,
  MulticriteriaWeights,
  Need,
  NeedCoverage,
  ObjectLink,
  Organization,
  QuarantineRecord,
  Shipment,
  ShipmentUnit,
  SupplyItem,
  User,
  UserScope,
} from "@/modules/domain/types";

const createdAt = "2026-07-02T08:00:00.000-04:00";
const schemaVersion = "mcl.v0.1";

export const users: User[] = [
  {
    id: "user-demo-admin",
    name: "Operador Demonstrativo",
    email: "operador.demo@mcl.invalid",
    active: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "user-demo-auditor",
    name: "Auditor Demonstrativo",
    email: "auditor.demo@mcl.invalid",
    active: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "user-demo-viewer",
    name: "Comando Demonstrativo",
    email: "comando.demo@mcl.invalid",
    active: true,
    createdAt,
    updatedAt: createdAt,
  },
];

export const organizations: Organization[] = [
  {
    id: "org-provedor-alfa",
    code: "OP-ALFA",
    name: "Orgao Provedor Alfa",
    type: "ORGAO_PROVEDOR",
    synthetic: true,
    active: true,
  },
  {
    id: "org-bravo",
    code: "OA-BRAVO",
    name: "Organizacao Apoiada Bravo",
    type: "ORGANIZACAO_APOIADA",
    parentId: "org-provedor-alfa",
    synthetic: true,
    active: true,
  },
  {
    id: "org-delta",
    code: "OA-DELTA",
    name: "Organizacao Apoiada Delta",
    type: "ORGANIZACAO_APOIADA",
    parentId: "org-provedor-alfa",
    synthetic: true,
    active: true,
  },
];

export const userScopes: UserScope[] = [
  {
    userId: "user-demo-admin",
    organizationId: "org-provedor-alfa",
    supplyClass: "CLASSE_II",
    role: "ADMIN",
    validFrom: createdAt,
    active: true,
  },
  {
    userId: "user-demo-admin",
    organizationId: "org-provedor-alfa",
    supplyClass: "CLASSE_II",
    role: "LOGISTICS_MANAGER",
    validFrom: createdAt,
    active: true,
  },
  {
    userId: "user-demo-auditor",
    organizationId: "org-provedor-alfa",
    supplyClass: "CLASSE_II",
    role: "AUDITOR",
    validFrom: createdAt,
    active: true,
  },
  {
    userId: "user-demo-viewer",
    organizationId: "org-bravo",
    supplyClass: "CLASSE_II",
    role: "COMMAND_VIEWER",
    validFrom: createdAt,
    active: true,
  },
];

export const supplyItems: SupplyItem[] = [
  {
    id: "item-coturno",
    persistentCode: "MCL-ITEM-CLII-COTURNO",
    name: "Coturno operacional",
    description: "Item sintetico de fardamento para demonstracao de continuidade logistica.",
    supplyClass: "CLASSE_II",
    category: "FARDAMENTO",
    baseUnit: "par",
    active: true,
    synthetic: true,
  },
  {
    id: "item-gandola",
    persistentCode: "MCL-ITEM-CLII-GANDOLA",
    name: "Gandola",
    description: "Item sintetico de fardamento.",
    supplyClass: "CLASSE_II",
    category: "FARDAMENTO",
    baseUnit: "unidade",
    active: true,
    synthetic: true,
  },
  {
    id: "item-calca",
    persistentCode: "MCL-ITEM-CLII-CALCA",
    name: "Calca",
    description: "Item sintetico de fardamento.",
    supplyClass: "CLASSE_II",
    category: "FARDAMENTO",
    baseUnit: "unidade",
    active: true,
    synthetic: true,
  },
  {
    id: "item-camiseta",
    persistentCode: "MCL-ITEM-CLII-CAMISETA",
    name: "Camiseta meia-manga",
    description: "Item sintetico de fardamento.",
    supplyClass: "CLASSE_II",
    category: "FARDAMENTO",
    baseUnit: "unidade",
    active: true,
    synthetic: true,
  },
];

export const itemVariants: ItemVariant[] = [
  {
    id: "variant-coturno-42",
    itemId: "item-coturno",
    sku: "COT-OP-42-SYN",
    label: "Coturno operacional tamanho 42",
    size: "42",
    unit: "par",
    active: true,
  },
  {
    id: "variant-coturno-43",
    itemId: "item-coturno",
    sku: "COT-OP-43-SYN",
    label: "Coturno operacional tamanho 43",
    size: "43",
    unit: "par",
    active: true,
  },
  {
    id: "variant-gandola-m",
    itemId: "item-gandola",
    sku: "GAN-M-SYN",
    label: "Gandola M",
    size: "M",
    unit: "unidade",
    active: true,
  },
  {
    id: "variant-calca-42",
    itemId: "item-calca",
    sku: "CAL-42-SYN",
    label: "Calca tamanho 42",
    size: "42",
    unit: "unidade",
    active: true,
  },
  {
    id: "variant-camiseta-g",
    itemId: "item-camiseta",
    sku: "CAM-G-SYN",
    label: "Camiseta meia-manga G",
    size: "G",
    unit: "unidade",
    active: true,
  },
];

const source = {
  occurredAt: createdAt,
  recordedAt: "2026-07-02T08:05:00.000-04:00",
  confidence: 0.92,
  schemaVersion,
  dataNature: "informado" as const,
};

export const needs: Need[] = [
  {
    id: "need-coturno-200",
    persistentCode: "MCL-NEC-2026-0001",
    organizationId: "org-bravo",
    itemVariantId: "variant-coturno-42",
    quantityRequested: 200,
    quantityApproved: 200,
    priority: "ALTA",
    requiredAt: "2026-07-20T17:00:00.000-04:00",
    purpose: "Reposicao sintetica de fardamento para demonstrar cadeia completa Classe II.",
    status: "EM_ATENDIMENTO",
    sourceSystem: "SIM-NECESSIDADES",
    sourceRecordId: "NEC-SYN-0001",
    authorityLevel: "DEMONSTRATIVO",
    createdAt,
    updatedAt: "2026-07-02T10:00:00.000-04:00",
    ...source,
  },
  {
    id: "need-gandola-80",
    persistentCode: "MCL-NEC-2026-0002",
    organizationId: "org-delta",
    itemVariantId: "variant-gandola-m",
    quantityRequested: 80,
    quantityApproved: 60,
    priority: "MEDIA",
    requiredAt: "2026-07-24T17:00:00.000-04:00",
    purpose: "Demanda sintetica complementar para teste de dashboard.",
    status: "PENDENTE_COBERTURA",
    sourceSystem: "SIM-NECESSIDADES",
    sourceRecordId: "NEC-SYN-0002",
    authorityLevel: "DEMONSTRATIVO",
    createdAt,
    updatedAt: createdAt,
    ...source,
  },
  {
    id: "need-calca-120",
    persistentCode: "MCL-NEC-2026-0003",
    organizationId: "org-bravo",
    itemVariantId: "variant-calca-42",
    quantityRequested: 120,
    quantityApproved: 120,
    priority: "BAIXA",
    requiredAt: "2026-08-02T17:00:00.000-04:00",
    purpose: "Demanda sintetica para simular importacao e quarentena.",
    status: "PLANEJADA",
    sourceSystem: "SIM-NECESSIDADES",
    sourceRecordId: "NEC-SYN-0003",
    authorityLevel: "DEMONSTRATIVO",
    createdAt,
    updatedAt: createdAt,
    ...source,
  },
];

export const credits: Credit[] = [
  {
    id: "credit-001",
    persistentCode: "MCL-CRED-2026-0001",
    amount: 48000,
    availableAmount: 12800,
    planningCode: "PLN-SYN-CLII-2026",
    expenseNature: "339030-SYN",
    expiresAt: "2026-12-31T23:59:59.000-04:00",
    status: "DISPONIVEL",
    sourceSystem: "SIM-FINANCEIRO",
    sourceRecordId: "CRED-SYN-0001",
    ...source,
    dataNature: "validado",
  },
];

export const acquisitionInstruments: AcquisitionInstrument[] = [
  {
    id: "instrument-001",
    persistentCode: "MCL-AQ-2026-0001",
    type: "ATA_DE_REGISTRO_DE_PRECOS_SINTETICA",
    reference: "ARP-SYN-CLII-2026-01",
    supplierNameSynthetic: "Fornecedor Sintetico Horizonte",
    validFrom: "2026-06-01T00:00:00.000-04:00",
    validUntil: "2026-12-31T23:59:59.000-04:00",
    capacity: 600,
    status: "VIGENTE",
    sourceSystem: "SIM-AQUISICAO",
    sourceRecordId: "AQ-SYN-0001",
  },
];

export const commitments: Commitment[] = [
  {
    id: "commitment-001",
    persistentCode: "MCL-EMP-2026-0001",
    creditId: "credit-001",
    acquisitionInstrumentId: "instrument-001",
    amount: 19200,
    issuedAt: "2026-07-02T09:20:00.000-04:00",
    status: "EMITIDO",
    sourceSystem: "SIM-FINANCEIRO",
    sourceRecordId: "EMP-SYN-0001",
    confidence: 0.9,
  },
];

export const needCoverages: NeedCoverage[] = [
  {
    id: "coverage-stock-001",
    needId: "need-coturno-200",
    coverageType: "ESTOQUE",
    quantity: 120,
    status: "RESERVADO",
  },
  {
    id: "coverage-acq-001",
    needId: "need-coturno-200",
    coverageType: "AQUISICAO",
    quantity: 80,
    creditId: "credit-001",
    commitmentId: "commitment-001",
    status: "EM_EXECUCAO",
  },
  {
    id: "coverage-stock-002",
    needId: "need-gandola-80",
    coverageType: "ESTOQUE",
    quantity: 30,
    status: "PARCIAL",
  },
  {
    id: "coverage-transfer-001",
    needId: "need-calca-120",
    coverageType: "TRANSFERENCIA",
    quantity: 60,
    status: "PLANEJADO",
  },
];

export const lots: Lot[] = [
  {
    id: "lot-coturno-001",
    persistentCode: "MCL-LOT-2026-COT-001",
    itemVariantId: "variant-coturno-42",
    quantity: 200,
    manufacturedAt: "2026-06-15T00:00:00.000-04:00",
    receivedAt: "2026-07-04T09:00:00.000-04:00",
    supplierReferenceSynthetic: "NF-SYN-8471",
    status: "PARCIALMENTE_ENTREGUE",
  },
  {
    id: "lot-gandola-001",
    persistentCode: "MCL-LOT-2026-GAN-001",
    itemVariantId: "variant-gandola-m",
    quantity: 100,
    manufacturedAt: "2026-06-18T00:00:00.000-04:00",
    receivedAt: "2026-07-03T15:30:00.000-04:00",
    supplierReferenceSynthetic: "NF-SYN-8530",
    status: "ARMAZENADO",
  },
];

export const locations: Location[] = [
  {
    id: "loc-recebimento-alfa",
    code: "ALFA-REC",
    name: "Docas de recebimento Alfa",
    organizationId: "org-provedor-alfa",
    type: "RECEBIMENTO",
    synthetic: true,
  },
  {
    id: "loc-inspecao-alfa",
    code: "ALFA-INSP",
    name: "Area de inspecao Alfa",
    organizationId: "org-provedor-alfa",
    type: "INSPECAO",
    synthetic: true,
  },
  {
    id: "loc-armazem-alfa-a",
    code: "ALFA-ARM-A",
    name: "Armazem Alfa A",
    organizationId: "org-provedor-alfa",
    type: "ARMAZENAGEM",
    synthetic: true,
  },
  {
    id: "loc-expedicao-alfa",
    code: "ALFA-EXP",
    name: "Area de expedicao Alfa",
    organizationId: "org-provedor-alfa",
    type: "EXPEDICAO",
    synthetic: true,
  },
  {
    id: "loc-bravo-recebimento",
    code: "BRAVO-REC",
    name: "Recebimento Bravo",
    organizationId: "org-bravo",
    type: "DESTINO",
    synthetic: true,
  },
];

function makeUnit(index: number, state: LogisticsUnit["currentState"], locationId: string): LogisticsUnit {
  const box = String(index).padStart(3, "0");
  return {
    id: `unit-coturno-${box}`,
    persistentCode: `MCL-UL-2026-${box}`,
    lotId: "lot-coturno-001",
    itemVariantId: "variant-coturno-42",
    quantity: 20,
    unit: "par",
    qrToken: `ul-coturno-caixa-${box}`,
    currentState: state,
    currentLocationId: locationId,
    condition: index === 4 ? "AVARIA_LEVE_CORRIGIDA" : "CONFORME",
    confidence: index === 4 ? 0.76 : 0.91,
    sourceSystem: "SIM-ESTOQUE",
    sourceRecordId: `UL-SYN-${box}`,
    occurredAt: createdAt,
    recordedAt: createdAt,
    schemaVersion,
    dataNature: index === 4 ? "divergente" : "calculado",
    sourceEventId: index <= 6 ? "evt-013" : "evt-009",
    active: true,
    createdAt,
    updatedAt: "2026-07-06T15:15:00.000-04:00",
  };
}

export const logisticsUnits: LogisticsUnit[] = [
  makeUnit(1, "ENTREGUE", "loc-bravo-recebimento"),
  makeUnit(2, "EM_TRANSITO", "loc-expedicao-alfa"),
  makeUnit(3, "SEPARADO", "loc-expedicao-alfa"),
  makeUnit(4, "ENTREGUE", "loc-bravo-recebimento"),
  makeUnit(5, "RESERVADO", "loc-armazem-alfa-a"),
  makeUnit(6, "RESERVADO", "loc-armazem-alfa-a"),
  makeUnit(7, "ARMAZENADO", "loc-armazem-alfa-a"),
  makeUnit(8, "ARMAZENADO", "loc-armazem-alfa-a"),
  makeUnit(9, "DISPONIVEL", "loc-inspecao-alfa"),
  makeUnit(10, "AGUARDANDO_INSPECAO", "loc-recebimento-alfa"),
  {
    id: "unit-gandola-001",
    persistentCode: "MCL-UL-2026-011",
    lotId: "lot-gandola-001",
    itemVariantId: "variant-gandola-m",
    quantity: 50,
    unit: "unidade",
    qrToken: "ul-gandola-caixa-001",
    currentState: "ARMAZENADO",
    currentLocationId: "loc-armazem-alfa-a",
    condition: "CONFORME",
    confidence: 0.88,
    sourceSystem: "SIM-ESTOQUE",
    sourceRecordId: "UL-SYN-011",
    occurredAt: createdAt,
    recordedAt: createdAt,
    schemaVersion,
    dataNature: "calculado",
    active: true,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "unit-gandola-002",
    persistentCode: "MCL-UL-2026-012",
    lotId: "lot-gandola-001",
    itemVariantId: "variant-gandola-m",
    quantity: 50,
    unit: "unidade",
    qrToken: "ul-gandola-caixa-002",
    currentState: "DISPONIVEL",
    currentLocationId: "loc-armazem-alfa-a",
    condition: "CONFORME",
    confidence: 0.87,
    sourceSystem: "SIM-ESTOQUE",
    sourceRecordId: "UL-SYN-012",
    occurredAt: createdAt,
    recordedAt: createdAt,
    schemaVersion,
    dataNature: "calculado",
    active: true,
    createdAt,
    updatedAt: createdAt,
  },
];

export const shipments: Shipment[] = [
  {
    id: "shipment-001",
    persistentCode: "MCL-REM-2026-0001",
    originOrganizationId: "org-provedor-alfa",
    destinationOrganizationId: "org-bravo",
    plannedDepartureAt: "2026-07-06T10:00:00.000-04:00",
    actualDepartureAt: "2026-07-06T10:18:00.000-04:00",
    expectedDeliveryAt: "2026-07-06T16:00:00.000-04:00",
    actualDeliveryAt: "2026-07-06T15:15:00.000-04:00",
    status: "ENTREGUE_COM_DIVERGENCIA_CORRIGIDA",
    transportReferenceSynthetic: "TR-SYN-ALFA-BRAVO-01",
    confidence: 0.89,
  },
  {
    id: "shipment-002",
    persistentCode: "MCL-REM-2026-0002",
    originOrganizationId: "org-provedor-alfa",
    destinationOrganizationId: "org-delta",
    plannedDepartureAt: "2026-07-08T10:00:00.000-04:00",
    expectedDeliveryAt: "2026-07-08T17:00:00.000-04:00",
    status: "PLANEJADA",
    transportReferenceSynthetic: "TR-SYN-ALFA-DELTA-01",
    confidence: 0.82,
  },
];

export const shipmentUnits: ShipmentUnit[] = [
  { shipmentId: "shipment-001", logisticsUnitId: "unit-coturno-001", quantity: 20 },
  { shipmentId: "shipment-001", logisticsUnitId: "unit-coturno-002", quantity: 20 },
  { shipmentId: "shipment-001", logisticsUnitId: "unit-coturno-003", quantity: 20 },
  { shipmentId: "shipment-001", logisticsUnitId: "unit-coturno-004", quantity: 20 },
  { shipmentId: "shipment-002", logisticsUnitId: "unit-gandola-001", quantity: 50 },
];

export const documents: DocumentReference[] = [
  {
    id: "doc-need-001",
    title: "Referencia sintetica da necessidade de coturnos",
    documentType: "REFERENCIA_DEMONSTRATIVA",
    repository: "MCL-DEMO",
    externalReference: "DOC-SYN-NEC-0001",
    classificationLabel: "NAO_CLASSIFICADO_SINTETICO",
    synthetic: true,
    createdAt,
  },
];

export const objectLinks: ObjectLink[] = [
  {
    id: "link-need-credit",
    fromType: "NEED",
    fromId: "need-coturno-200",
    relationType: "COBERTO_POR_CREDITO",
    toType: "CREDIT",
    toId: "credit-001",
    sourceSystem: "MCL-DEMO",
    sourceRecordId: "LINK-SYN-0001",
    createdAt,
  },
  {
    id: "link-credit-commitment",
    fromType: "CREDIT",
    fromId: "credit-001",
    relationType: "GEROU_EMPENHO",
    toType: "COMMITMENT",
    toId: "commitment-001",
    sourceSystem: "MCL-DEMO",
    sourceRecordId: "LINK-SYN-0002",
    createdAt,
  },
  {
    id: "link-need-lot",
    fromType: "NEED",
    fromId: "need-coturno-200",
    relationType: "ATENDIDA_POR_LOTE",
    toType: "LOT",
    toId: "lot-coturno-001",
    sourceSystem: "MCL-DEMO",
    sourceRecordId: "LINK-SYN-0003",
    createdAt,
  },
  {
    id: "link-unit-shipment",
    fromType: "LOGISTICS_UNIT",
    fromId: "unit-coturno-001",
    relationType: "EM_REMESSA",
    toType: "SHIPMENT",
    toId: "shipment-001",
    sourceSystem: "MCL-DEMO",
    sourceRecordId: "LINK-SYN-0004",
    createdAt,
  },
];

function event(
  id: string,
  eventType: LogisticsEvent["eventType"],
  objectType: string,
  objectId: string,
  occurredAt: string,
  payload: Record<string, unknown>,
  locationId?: string,
  condition?: string,
): LogisticsEvent {
  return {
    id,
    persistentCode: `MCL-EVT-2026-${id.replace("evt-", "").padStart(4, "0")}`,
    eventType,
    occurredAt,
    recordedAt: occurredAt,
    objectType,
    objectId,
    quantity: objectType === "LOGISTICS_UNIT" ? 20 : 0,
    unit: objectType === "LOGISTICS_UNIT" ? "par" : "registro",
    locationId,
    condition,
    sourceSystem: "MCL-DEMO",
    sourceRecordId: `SRC-${id}`,
    actorId: "user-demo-admin",
    idempotencyKey: `seed-${id}`,
    schemaVersion,
    authorityLevel: "DEMONSTRATIVO",
    confidence: eventType === "DIVERGENCIA_REGISTRADA" ? 0.74 : 0.9,
    dataNature: eventType === "DIVERGENCIA_REGISTRADA" ? "divergente" : "validado",
    payload,
    createdAt: occurredAt,
  };
}

export const events: LogisticsEvent[] = [
  event("evt-001", "NECESSIDADE_CRIADA", "NEED", "need-coturno-200", "2026-07-02T08:10:00.000-04:00", {
    purpose: "Registro inicial da demanda sintetica.",
  }),
  event("evt-002", "NECESSIDADE_APROVADA", "NEED", "need-coturno-200", "2026-07-02T08:30:00.000-04:00", {
    approvedQuantity: 200,
  }),
  event("evt-003", "CREDITO_DISPONIBILIZADO", "CREDIT", "credit-001", "2026-07-02T09:00:00.000-04:00", {
    amount: 48000,
  }),
  event("evt-004", "INSTRUMENTO_VINCULADO", "ACQUISITION_INSTRUMENT", "instrument-001", "2026-07-02T09:10:00.000-04:00", {
    needId: "need-coturno-200",
  }),
  event("evt-005", "EMPENHO_EMITIDO", "COMMITMENT", "commitment-001", "2026-07-02T09:20:00.000-04:00", {
    amount: 19200,
  }),
  event("evt-006", "FORNECIMENTO_INICIADO", "LOT", "lot-coturno-001", "2026-07-03T08:00:00.000-04:00", {
    supplierReferenceSynthetic: "NF-SYN-8471",
  }),
  event(
    "evt-007",
    "MATERIAL_RECEBIDO",
    "LOGISTICS_UNIT",
    "unit-coturno-001",
    "2026-07-04T09:00:00.000-04:00",
    { invoiceSynthetic: "NF-SYN-8471" },
    "loc-recebimento-alfa",
    "A_CONFERIR",
  ),
  event(
    "evt-008",
    "INSPECAO_CONCLUIDA",
    "LOGISTICS_UNIT",
    "unit-coturno-001",
    "2026-07-04T11:00:00.000-04:00",
    { accepted: true, inspectorNote: "Conferencia sintetica sem restricoes." },
    "loc-inspecao-alfa",
    "CONFORME",
  ),
  event(
    "evt-009",
    "MATERIAL_ARMAZENADO",
    "LOGISTICS_UNIT",
    "unit-coturno-001",
    "2026-07-04T15:00:00.000-04:00",
    { shelf: "A1-SYN" },
    "loc-armazem-alfa-a",
    "CONFORME",
  ),
  event(
    "evt-010",
    "ESTOQUE_RESERVADO",
    "LOGISTICS_UNIT",
    "unit-coturno-001",
    "2026-07-05T09:30:00.000-04:00",
    { needId: "need-coturno-200" },
    "loc-armazem-alfa-a",
    "CONFORME",
  ),
  event(
    "evt-011",
    "MATERIAL_SEPARADO",
    "LOGISTICS_UNIT",
    "unit-coturno-001",
    "2026-07-06T08:00:00.000-04:00",
    { shipmentId: "shipment-001" },
    "loc-expedicao-alfa",
    "CONFORME",
  ),
  event(
    "evt-012",
    "REMESSA_EXPEDIDA",
    "LOGISTICS_UNIT",
    "unit-coturno-001",
    "2026-07-06T10:18:00.000-04:00",
    { shipmentId: "shipment-001", transportReferenceSynthetic: "TR-SYN-ALFA-BRAVO-01" },
    "loc-expedicao-alfa",
    "CONFORME",
  ),
  event(
    "evt-013",
    "MATERIAL_ENTREGUE",
    "LOGISTICS_UNIT",
    "unit-coturno-001",
    "2026-07-06T15:15:00.000-04:00",
    { receiverSynthetic: "Equipe de recebimento Bravo" },
    "loc-bravo-recebimento",
    "CONFORME",
  ),
  event(
    "evt-014",
    "DIVERGENCIA_REGISTRADA",
    "LOGISTICS_UNIT",
    "unit-coturno-004",
    "2026-07-06T15:20:00.000-04:00",
    { severity: "ALTA", expected: "20 pares conformes", observed: "20 pares com embalagem avariada" },
    "loc-bravo-recebimento",
    "AVARIA_EMBALAGEM",
  ),
  {
    ...event(
      "evt-015",
      "EVENTO_CORRIGIDO",
      "LOGISTICS_UNIT",
      "unit-coturno-004",
      "2026-07-06T16:00:00.000-04:00",
      { correctedEventId: "evt-014", correction: "Avaria limitada a embalagem externa; material aceito." },
      "loc-bravo-recebimento",
      "AVARIA_LEVE_CORRIGIDA",
    ),
    correctionOfEventId: "evt-014",
  },
];

export const eventRelations: EventRelation[] = [
  { eventId: "evt-001", relatedObjectType: "ORGANIZATION", relatedObjectId: "org-bravo", relationType: "DEMANDANTE" },
  { eventId: "evt-004", relatedObjectType: "NEED", relatedObjectId: "need-coturno-200", relationType: "ATENDE" },
  { eventId: "evt-005", relatedObjectType: "CREDIT", relatedObjectId: "credit-001", relationType: "USA_CREDITO" },
  { eventId: "evt-013", relatedObjectType: "SHIPMENT", relatedObjectId: "shipment-001", relationType: "ENTREGA_REMESSA" },
  { eventId: "evt-014", relatedObjectType: "NEED", relatedObjectId: "need-coturno-200", relationType: "AFETA" },
];

export const divergences: Divergence[] = [
  {
    id: "div-001",
    persistentCode: "MCL-DIV-2026-0001",
    title: "Embalagem avariada em caixa de coturnos",
    severity: "ALTA",
    status: "CORRIGIDA",
    objectType: "LOGISTICS_UNIT",
    objectId: "unit-coturno-004",
    expected: "20 pares conformes",
    observed: "20 pares com embalagem externa avariada",
    sourceSystem: "MCL-DEMO",
    sourceRecordId: "SRC-evt-014",
    confidence: 0.74,
    detectedAt: "2026-07-06T15:20:00.000-04:00",
    correctedByEventId: "evt-015",
  },
];

export const connectors: ConnectorHealth[] = [
  {
    id: "connector-needs",
    name: "Simulador de necessidades",
    sourceSystem: "SIM-NECESSIDADES",
    status: "SAUDAVEL",
    lastRunAt: "2026-07-02T10:00:00.000-04:00",
    lastSuccessAt: "2026-07-02T10:00:00.000-04:00",
    latencyMs: 188,
    recordsImported: 3,
    quarantinedRecords: 0,
    message: "Carga sintetica validada.",
  },
  {
    id: "connector-finance",
    name: "Simulador financeiro",
    sourceSystem: "SIM-FINANCEIRO",
    status: "ATRASADO",
    lastRunAt: "2026-07-02T06:45:00.000-04:00",
    lastSuccessAt: "2026-07-02T06:45:00.000-04:00",
    latencyMs: 940,
    recordsImported: 2,
    quarantinedRecords: 1,
    message: "Ultima sincronizacao fora da janela demonstrativa.",
  },
  {
    id: "connector-transport",
    name: "Simulador de transporte",
    sourceSystem: "SIM-TRANSPORTE",
    status: "FALHA",
    lastRunAt: "2026-07-02T09:40:00.000-04:00",
    lastSuccessAt: "2026-07-01T17:10:00.000-04:00",
    latencyMs: 0,
    recordsImported: 0,
    quarantinedRecords: 2,
    message: "Falha sintetica de endpoint; nenhum dado real foi consultado.",
  },
];

export const quarantine: QuarantineRecord[] = [
  {
    id: "quarantine-001",
    sourceSystem: "SIM-FINANCEIRO",
    sourceRecordId: "EMP-SYN-INVALIDO",
    reason: "Valor negativo rejeitado pela validacao server-side.",
    payload: { amount: -1, synthetic: true },
    createdAt: "2026-07-02T09:55:00.000-04:00",
  },
  {
    id: "quarantine-002",
    sourceSystem: "SIM-TRANSPORTE",
    sourceRecordId: "TR-SYN-INCOMPLETO",
    reason: "Remessa sem destino foi mantida em quarentena.",
    payload: { destinationOrganizationId: null, synthetic: true },
    createdAt: "2026-07-02T09:56:00.000-04:00",
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: "audit-001",
    occurredAt: "2026-07-02T10:00:00.000-04:00",
    actorId: "user-demo-admin",
    action: "AUTH_DEMO_LOGIN",
    resourceType: "SESSION",
    resourceId: "demo-session",
    organizationId: "org-provedor-alfa",
    requestId: "req-seed-001",
    userAgent: "seed",
    outcome: "SUCESSO",
    reason: "Modo demonstrativo habilitado.",
    metadata: { synthetic: true },
  },
  {
    id: "audit-002",
    occurredAt: "2026-07-02T10:01:00.000-04:00",
    actorId: "user-demo-admin",
    action: "QR_RESOLVIDO",
    resourceType: "LOGISTICS_UNIT",
    resourceId: "unit-coturno-001",
    organizationId: "org-provedor-alfa",
    requestId: "req-seed-002",
    userAgent: "seed",
    outcome: "SUCESSO",
    reason: "Passaporte consultado no seed.",
    metadata: { qrToken: "ul-coturno-caixa-001" },
  },
];

export const multicriteriaWeights: MulticriteriaWeights[] = [
  {
    id: "weights-demo-v1",
    version: "demo-2026-07-02",
    urgency: 35,
    operationalImpact: 25,
    stockRisk: 20,
    logisticsLeadTime: 10,
    financialCoverage: 10,
    acceptedByHuman: false,
    humanJustification: "Pesos demonstrativos pendentes de aprovacao institucional.",
  },
];

export function createDemoState(): DemoState {
  return {
    users,
    userScopes,
    organizations,
    supplyItems,
    itemVariants,
    needs,
    credits,
    acquisitionInstruments,
    commitments,
    needCoverages,
    lots,
    locations,
    logisticsUnits,
    shipments,
    shipmentUnits,
    documents,
    objectLinks,
    events,
    eventRelations,
    divergences,
    connectors,
    quarantine,
    auditLogs,
    multicriteriaWeights,
  };
}
